# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20161201_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='referrer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='language_name',
            field=models.CharField(blank=True, choices=[('sv', 'Swedish'), ('eu', 'Basque'), ('hr', 'Croatian'), ('pl', 'Polish'), ('kn', 'Kannada'), ('hu', 'Hungarian'), ('io', 'Ido'), ('ml', 'Malayalam'), ('is', 'Icelandic'), ('ast', 'Asturian'), ('km', 'Khmer'), ('mr', 'Marathi'), ('th', 'Thai'), ('es-co', 'Colombian Spanish'), ('os', 'Ossetic'), ('nb', 'Norwegian Bokmal'), ('et', 'Estonian'), ('te', 'Telugu'), ('eo', 'Esperanto'), ('ga', 'Irish'), ('sk', 'Slovak'), ('cy', 'Welsh'), ('mk', 'Macedonian'), ('sw', 'Swahili'), ('ru', 'Russian'), ('en-au', 'Australian English'), ('sr-latn', 'Serbian Latin'), ('fa', 'Persian'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ne', 'Nepali'), ('pt-br', 'Brazilian Portuguese'), ('en', 'English'), ('lt', 'Lithuanian'), ('de', 'German'), ('he', 'Hebrew'), ('mn', 'Mongolian'), ('ka', 'Georgian'), ('es-ar', 'Argentinian Spanish'), ('fr', 'French'), ('gd', 'Scottish Gaelic'), ('sq', 'Albanian'), ('es-ni', 'Nicaraguan Spanish'), ('ta', 'Tamil'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('es-ve', 'Venezuelan Spanish'), ('tr', 'Turkish'), ('es', 'Spanish'), ('bs', 'Bosnian'), ('tt', 'Tatar'), ('sr', 'Serbian'), ('ja', 'Japanese'), ('lb', 'Luxembourgish'), ('fi', 'Finnish'), ('el', 'Greek'), ('da', 'Danish'), ('br', 'Breton'), ('ko', 'Korean'), ('uk', 'Ukrainian'), ('zh-hans', 'Simplified Chinese'), ('sl', 'Slovenian'), ('bg', 'Bulgarian'), ('it', 'Italian'), ('gl', 'Galician'), ('vi', 'Vietnamese'), ('zh-hant', 'Traditional Chinese'), ('be', 'Belarusian'), ('kk', 'Kazakh'), ('es-mx', 'Mexican Spanish'), ('ca', 'Catalan'), ('id', 'Indonesian'), ('fy', 'Frisian'), ('cs', 'Czech'), ('nn', 'Norwegian Nynorsk'), ('pa', 'Punjabi'), ('ia', 'Interlingua'), ('nl', 'Dutch'), ('af', 'Afrikaans'), ('az', 'Azerbaijani'), ('lv', 'Latvian'), ('en-gb', 'British English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('udm', 'Udmurt'), ('my', 'Burmese')], max_length=7),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'unapproved'), (1, 'approved'), (2, 'complete'), (3, 'all')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='carrier',
            field=models.IntegerField(choices=[(0, ''), (1, 'txt.att.net'), (2, 'messaging.sprintpcs.com'), (3, 'tmomail.net'), (4, 'vzwpix.com'), (5, 'sms.alltelwireless.com'), (6, 'sms.myboostmobile.com'), (7, 'cwemail.com'), (8, 'gocbw.com'), (9, 'sms.mycricket.com'), (10, 'mymetropcs.com'), (11, 'qwestmp.com'), (12, 'sms.rogers.com'), (13, 'msg.telus.com'), (14, 'email.uscc.net'), (15, 'vmobl.com')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('sv', 'Swedish'), ('eu', 'Basque'), ('hr', 'Croatian'), ('pl', 'Polish'), ('kn', 'Kannada'), ('hu', 'Hungarian'), ('io', 'Ido'), ('ml', 'Malayalam'), ('is', 'Icelandic'), ('ast', 'Asturian'), ('km', 'Khmer'), ('mr', 'Marathi'), ('th', 'Thai'), ('es-co', 'Colombian Spanish'), ('os', 'Ossetic'), ('nb', 'Norwegian Bokmal'), ('et', 'Estonian'), ('te', 'Telugu'), ('eo', 'Esperanto'), ('ga', 'Irish'), ('sk', 'Slovak'), ('cy', 'Welsh'), ('mk', 'Macedonian'), ('sw', 'Swahili'), ('ru', 'Russian'), ('en-au', 'Australian English'), ('sr-latn', 'Serbian Latin'), ('fa', 'Persian'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ne', 'Nepali'), ('pt-br', 'Brazilian Portuguese'), ('en', 'English'), ('lt', 'Lithuanian'), ('de', 'German'), ('he', 'Hebrew'), ('mn', 'Mongolian'), ('ka', 'Georgian'), ('es-ar', 'Argentinian Spanish'), ('fr', 'French'), ('gd', 'Scottish Gaelic'), ('sq', 'Albanian'), ('es-ni', 'Nicaraguan Spanish'), ('ta', 'Tamil'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('es-ve', 'Venezuelan Spanish'), ('tr', 'Turkish'), ('es', 'Spanish'), ('bs', 'Bosnian'), ('tt', 'Tatar'), ('sr', 'Serbian'), ('ja', 'Japanese'), ('lb', 'Luxembourgish'), ('fi', 'Finnish'), ('el', 'Greek'), ('da', 'Danish'), ('br', 'Breton'), ('ko', 'Korean'), ('uk', 'Ukrainian'), ('zh-hans', 'Simplified Chinese'), ('sl', 'Slovenian'), ('bg', 'Bulgarian'), ('it', 'Italian'), ('gl', 'Galician'), ('vi', 'Vietnamese'), ('zh-hant', 'Traditional Chinese'), ('be', 'Belarusian'), ('kk', 'Kazakh'), ('es-mx', 'Mexican Spanish'), ('ca', 'Catalan'), ('id', 'Indonesian'), ('fy', 'Frisian'), ('cs', 'Czech'), ('nn', 'Norwegian Nynorsk'), ('pa', 'Punjabi'), ('ia', 'Interlingua'), ('nl', 'Dutch'), ('af', 'Afrikaans'), ('az', 'Azerbaijani'), ('lv', 'Latvian'), ('en-gb', 'British English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('udm', 'Udmurt'), ('my', 'Burmese')], max_length=7),
        ),
    ]
