# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-05 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fixing phone number field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='referrer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referring_volunteer', to=settings.AUTH_USER_MODEL),
        ),
    ]
