# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_testing change to referral type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='referrer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
