# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-05 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reverting change from User to user id'),
    ]

    operations = [
    ]
