# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_reverting change from User to user id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='referrer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
